name: Build and Test - Windows

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-2022]

    steps:
      - name: Add Microsoft.VisualStudio.Component.WinXP (via PowerShell)
        shell: powershell
        run: |
            Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
            $WorkLoads = '--add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --add Microsoft.Component.VC.Runtime.UCRTSDK --add Microsoft.VisualStudio.Component.WinXP'
            $Arguments = ('/c', "vs_installer.exe", 'modify', '--channelId', 'VisualStudio.17.Release', '--productId', 'Microsoft.VisualStudio.Product.Enterprise', $WorkLoads, '--quiet', '--norestart', '--nocache')
            $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
            if ($process.ExitCode -eq 0) {
                Write-Host "components have been successfully added"
            } else {
                Write-Host "components were not installed"
            }

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build - Win32
        run: |
          src\Build_Win32.cmd

